apiVersion: v2
type: application
name: snapshot-controller
version: 5.0.0
appVersion: "v8.4.0"
kubeVersion: ">= 1.25.0-0"
icon: https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/artwork/sandbox-artwork/icon/color.svg
maintainers:
  - name: The Piraeus Maintainers
    url: https://github.com/piraeusdatastore/
description: |
  Deploys a Snapshot Controller in a cluster. Snapshot Controllers are often bundled with the Kubernetes distribution,
  this chart is meant for cases where it is not.
keywords:
  - storage
  - snapshot
  - validation
home: https://github.com/piraeusdatastore/helm-charts
sources:
  - https://github.com/kubernetes-csi/external-snapshotter/
