apiVersion: v2
name: linstor-affinity-controller
description: |
  Deploys the LINSTOR Affinity Controller. It periodically checks the state of Piraeus/LINSTOR volumes compared to
  PersistentVolumes (PV), and updates the PV Affinity if changes are detected.
type: application
icon: https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/artwork/sandbox-artwork/icon/color.svg
maintainers:
  - name: The Piraeus Maintainers
    url: https://github.com/piraeusdatastore/
keywords:
  - storage
home: https://github.com/piraeusdatastore/helm-charts
sources:
  - https://github.com/piraeusdatastore/linstor-affinity-controller

version: 1.5.0
appVersion: "v1.2.0"
