{{- if .Values.webhook.enabled }}
{{- if .Values.webhook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "conversion-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conversion-webhook.labels" . | nindent 4 }}
{{- end }}
{{- end }}
