{{- if and .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conversion-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conversion-webhook.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.args.port }}
      name: https
  selector:
    {{- include "conversion-webhook.selectorLabels" . | nindent 4 }}
{{- end }}
