apiVersion: v2
type: application
name: snapshot-validation-webhook
version: 1.4.2
appVersion: "v6.0.1"
icon: https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/artwork/sandbox-artwork/icon/color.svg
maintainers:
  - name: The Piraeus Maintainers
    url: https://github.com/piraeusdatastore/
description: |
  Deploys the snapshot-validation-webhook and configures your cluster to validate every `VolumeSnapshot` and
  `VolumeSnapshotContent` resource by sending it to the webhook.
keywords:
  - storage
  - snapshot
  - validation
home: https://github.com/piraeusdatastore/helm-charts
sources:
  - https://github.com/kubernetes-csi/external-snapshotter/
annotations:
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/piraeus-charts/snapshot-controller
